### ISSUE TITLE
Please update the add-on

### ISSUE THREAD

**Issue by HQYang1979** [RhettTien/Batch-Editor-Tools#1]
Please update the add-on so that it can work in new versions of Anki. Your idea is excellent.

**Comment by RhettTien** [comment]
The test in the `23.10.1 Qt5` version is no problem. Please describe the version you are using and the version of the operating system in detail so that I can improve it.

**Comment by HQYang1979** [comment]
> The test in the `23.10.1 Qt5` version is no problem. Please describe the version you are using and the version of the operating system in detail so that I can improve it.

anki 23.10.1 qt6, win11

**Comment by RhettTien** [comment]
> > The test in the `23.10.1 Qt5` version is no problem. Please describe the version you are using and the version of the operating system in detail so that I can improve it.
> 
> anki 23.10.1 qt6, win11

It can be used normally in the 'win11-23H2' and '23.10.1 Qt6' version, please carefully check the ’/‘ or ’\\‘ in the path to make sure there is no problem with the format. There are detailed instructions in the help document.
https://ankiweb.net/shared/info/1609139780

**Comment by RhettTien** [comment]
> > The test in the `23.10.1 Qt5` version is no problem. Please describe the version you are using and the version of the operating system in detail so that I can improve it.
> 
> anki 23.10.1 qt6, win11

Hi, the last version did have a problem, although I didn't reproduce it, now I've updated the UI interface, and it's easier to use, welcome to the new version!
https://ankiweb.net/shared/info/1609139780
